name: E2E Test
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install --frozen-lockfile
      - name: E2E Tests
        uses: cypress-io/github-action@v3.0.3
        with:
          start: npm start
          wait-on: "http://localhost:3000"
